<script lang="ts">
  import { onMount } from 'svelte';
  import { createApiClient } from '$lib/api/client';
  import FuzzySelect from '$lib/forms/FuzzySelect.svelte';
  type Member = { id: string; username: string; nickname?: string; bot: boolean };
  type Role = { id: number; name: string };
  let members = $state<Member[]>([]); let roles = $state<Role[]>([]); let memberID = $state(''); let role = $state(''); let searchMembers = $state(''); let error = $state(''); let saving = $state(false); let loading = $state(true);
  let memberOptions = $derived(members.map((member) => ({ value: member.id, label: member.nickname ? `${member.nickname} · ${member.username}` : member.username, detail: 'Discord member' })));
  onMount(async () => { try { const api = createApiClient(); const [discord, catalog] = await Promise.all([api.get<{ members: Member[] }>('/api/v1/discord/resources'), api.get<Role[]>('/api/v1/catalog/roles')]); members = discord.members.filter((member) => !member.bot); roles = catalog; } catch (cause) { error = cause instanceof Error ? cause.message : 'Could not load Discord members and roles'; } finally { loading = false; } });
  async function submit(event: SubmitEvent) { event.preventDefault(); saving = true; error = ''; try { const player = await createApiClient().post<{ id: string }>('/api/v1/players', { headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: memberID, role }) }); window.location.href = `/players/${player.id}/edit`; } catch (cause) { error = cause instanceof Error ? cause.message : 'Could not create player'; } finally { saving = false; } }
</script>
<svelte:head><title>New player | Betrayal Admin</title></svelte:head>
<main class="page-shell"><div class="form-page"><a href="/players" class="back-link">← Back to roster</a><p class="eyebrow">Roster / onboarding</p><h1 class="display-title">Add player</h1><p class="lede">Bring a Discord member into the game roster, then give them their starting role.</p>{#if error}<p role="alert" class="state state-error">{error}</p>{/if}{#if loading}<p role="status" class="state">Loading available Discord members…</p>{:else}<form onsubmit={submit} class="form-card"><div class="form-intro"><span class="form-step">01</span><div><h2>Identity & role</h2><p>Names are shown in the roster; Discord IDs stay behind the scenes.</p></div></div><FuzzySelect label="Discord member" placeholder="Search by username or nickname…" options={memberOptions} bind:value={memberID} emptyText="No Discord members match that search" /><label class="field">Starting role<select bind:value={role} required><option value="">Select a role</option>{#each roles as item}<option value={item.name}>{item.name}</option>{/each}</select></label>{#if members.length === 0}<p class="notice">No Discord members were returned. Check that Discord is connected and the bot can view guild members.</p>{/if}<div class="form-actions"><a href="/players" class="btn">Cancel</a><button disabled={saving || !memberID || !role} class="btn btn-primary">{saving ? 'Creating…' : 'Create player'}</button></div></form>{/if}</div></main>
