<script lang="ts">
  import { onMount } from 'svelte';
  import { createApiClient } from '$lib/api/client';
  import FuzzySelect from '$lib/forms/FuzzySelect.svelte';
  type Entry = { name: string; kind: string; channel_id?: string; label?: string; status: string; note?: string };
  type Data = { discord_connected: boolean; entries: Entry[]; summary: { total: number; missing: number; configured: number; orphaned: number; unverified: number } };
  type DiscordChannel = { id: string; guild_id: string; name: string; type: string; category?: string };
  type DiscordResources = { channels: DiscordChannel[]; guilds: { id: string; name: string }[] };
  let resources = $state<DiscordResources | null>(null);
  let selectedGuild = $state('');
  let selectedKind = $state('vote');
  let selectedChannel = $state('');
  let messageID = $state('');
  let data = $state<Data | null>(null); let error = $state<string | null>(null); let busy = $state(false); const api = createApiClient();
  let availableChannels = $derived((resources?.channels ?? []).filter((channel) => channel.guild_id === selectedGuild));
  let channelOptions = $derived(availableChannels.map((channel) => ({ value: channel.id, label: `#${channel.name}`, detail: channel.category || 'Uncategorized' })));
  async function load() { try { data = await api.get<Data>('/api/v1/ops/channels'); error = null; } catch (e) { error = e instanceof Error ? e.message : 'Could not load channels'; } }
  async function update(event: SubmitEvent) { event.preventDefault(); busy = true; try { data = await api.post<Data>('/api/v1/ops/channels', { body: JSON.stringify({ kind: selectedKind, channel_id: selectedChannel, message_id: messageID }), headers: { 'Content-Type': 'application/json' } }); selectedChannel = ''; messageID = ''; } catch (e) { error = e instanceof Error ? e.message : 'Could not update channel'; } finally { busy = false; } }
  async function remove(entry: Entry) { if (!entry.channel_id || !confirm(`Delete ${entry.name} ${entry.channel_id}?`)) return; busy = true; try { await api.delete(`/api/v1/ops/channels/${entry.kind}/${entry.channel_id}`); await load(); } catch (e) { error = e instanceof Error ? e.message : 'Could not delete channel'; } finally { busy = false; } }
  onMount(async () => { await load(); try { resources = await api.get<DiscordResources>('/api/v1/discord/resources'); selectedGuild = resources.guilds[0]?.id ?? ''; } catch { resources = null; } });
</script>
<svelte:head><title>Channels | Betrayal Admin</title></svelte:head>
<main class="min-h-screen bg-slate-950 p-6 text-slate-100"><div class="mx-auto max-w-6xl">
  <header class="border-b border-slate-800 pb-8"><p class="text-xs font-semibold uppercase tracking-[0.2em] text-violet-300">Game operations</p><h1 class="mt-3 text-4xl font-semibold">Channels</h1><p class="mt-3 max-w-2xl text-slate-400">Configure game channels from the complete Discord resource list. Search by channel name, category, or ID instead of relying on a long native dropdown.</p></header>
  {#if error}<p role="alert" class="mt-6 rounded border border-red-500/40 bg-red-500/5 p-4 text-red-200">{error}</p>{/if}
  {#if !data && !error}<p role="status" class="py-10 text-slate-300">Loading channels…</p>
  {:else if data}<div class="mt-6 grid gap-4 sm:grid-cols-4"><div class="rounded border border-slate-800 bg-[#0d111b] p-4"><p class="text-xs uppercase text-slate-500">Configured</p><p class="mt-2 text-2xl">{data.summary.configured}</p></div><div class="rounded border border-slate-800 bg-[#0d111b] p-4"><p class="text-xs uppercase text-slate-500">Missing</p><p class="mt-2 text-2xl text-amber-200">{data.summary.missing}</p></div><div class="rounded border border-slate-800 bg-[#0d111b] p-4"><p class="text-xs uppercase text-slate-500">Orphaned</p><p class="mt-2 text-2xl">{data.summary.orphaned}</p></div><div class="rounded border border-slate-800 bg-[#0d111b] p-4"><p class="text-xs uppercase text-slate-500">Discord</p><p class="mt-2 text-2xl">{data.discord_connected ? 'Connected' : 'Disabled'}</p></div></div>
    <section class="mt-8 rounded border border-slate-800 bg-[#0d111b] p-5"><h2 class="text-xl font-semibold">Configure a channel</h2><form class="mt-5 grid gap-4 md:grid-cols-2" onsubmit={update}><label class="block text-sm text-slate-300">Configuration<select bind:value={selectedKind} class="mt-2 w-full bg-slate-900 p-3"><option value="vote">Vote funnel</option><option value="action">Action funnel</option><option value="log">Command log</option><option value="admin">Admin channel</option><option value="lifeboard">Lifeboard</option></select></label>{#if resources}<label class="block text-sm text-slate-300">Discord server<select bind:value={selectedGuild} class="mt-2 w-full bg-slate-900 p-3">{#each resources.guilds as guild}<option value={guild.id}>{guild.name}</option>{/each}</select></label><div class="md:col-span-2"><FuzzySelect label="Discord channel" placeholder="Search #channel, category, or ID…" options={channelOptions} bind:value={selectedChannel} disabled={busy} emptyText="No channels match that search" /></div>{:else}<label class="block text-sm text-slate-300 md:col-span-2">Channel ID<input bind:value={selectedChannel} required placeholder="Discord channel ID" class="mt-2 w-full bg-slate-900 p-3" /></label>{/if}<label class="block text-sm text-slate-300">Lifeboard message ID <span class="text-slate-500">(only needed for lifeboard)</span><input bind:value={messageID} placeholder="Optional message ID" class="mt-2 w-full bg-slate-900 p-3" /></label><div class="flex items-end"><button class="border border-emerald-400 px-4 py-3 text-emerald-200 disabled:opacity-50" disabled={busy || !selectedChannel}>Save channel configuration</button></div></form></section>
    <section class="mt-8"><h2 class="text-xl font-semibold">Current configuration</h2><div class="mt-4 grid gap-3 md:grid-cols-2">{#each data.entries as entry (entry.kind + entry.name + entry.channel_id)}<article class="rounded border border-slate-700 bg-[#0d111b] p-4"><div class="flex justify-between gap-4"><h3>{entry.name}</h3><span class="text-sm text-slate-400">{entry.status}</span></div>{#if entry.channel_id}<p class="mt-2 text-lg text-slate-200">{entry.label ?? 'Configured Discord channel'}</p>{/if}{#if entry.note}<p class="mt-2 text-sm text-slate-400">{entry.note}</p>{/if}{#if entry.kind === 'admin' && entry.channel_id}<button class="mt-3 text-sm text-red-300" disabled={busy} onclick={() => remove(entry)}>Remove admin channel</button>{/if}</article>{/each}</div></section>{/if}
</div></main>
