<script lang="ts">
  import { onMount } from 'svelte'; import { createApiClient } from '$lib/api/client';
  type Setup = { player_count?: number; deceptionist_count?: number; pool?: { random_pool: { name: string }[]; deception_options: { name: string }[][] } };
  let setup = $state<Setup | null>(null); let error = $state<string | null>(null); let busy = $state(false); const api = createApiClient();
  async function load() { try { setup = await api.get<Setup>('/api/v1/ops/setup'); } catch (e) { error = e instanceof Error ? e.message : 'Could not load setup'; } }
  async function generate(event: SubmitEvent) { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); busy = true; try { setup = await api.post<Setup>('/api/v1/ops/setup', { body: JSON.stringify({ player_count: Number(form.get('player_count')), deceptionist_count: Number(form.get('deceptionist_count')) }), headers: { 'Content-Type': 'application/json' } }); } catch (e) { error = e instanceof Error ? e.message : 'Could not generate role pool'; } finally { busy = false; } }
  onMount(load);
</script>
<svelte:head><title>Setup | Betrayal Admin</title></svelte:head>
<main class="min-h-screen bg-slate-950 p-6 text-slate-100"><div class="mx-auto max-w-4xl"><h1 class="text-3xl font-semibold">Game Setup</h1>{#if error}<p role="alert" class="mt-6 text-red-300">{error}</p>{/if}<form class="mt-8 flex flex-wrap gap-3" onsubmit={generate}><input name="player_count" type="number" min="0" required placeholder="Players" class="bg-slate-900 p-2" /><input name="deceptionist_count" type="number" min="0" required placeholder="Deceptionists" class="bg-slate-900 p-2" /><button class="border border-emerald-400 px-4 py-2" disabled={busy}>Generate role pool</button></form>{#if setup?.pool}<section class="mt-8 border border-slate-700 p-6"><h2 class="text-xl">Generated pool</h2><p class="mt-3 text-slate-400">{setup.player_count} players · {setup.deceptionist_count} deceptionists</p><div class="mt-4 flex flex-wrap gap-2">{#each setup.pool.random_pool as role (role.name)}<span class="border border-slate-600 px-2 py-1">{role.name}</span>{/each}</div></section>{/if}</div></main>
