// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: ability_category.sql

package models

import (
	"context"
)

const createAbilityCategoryJoin = `-- name: CreateAbilityCategoryJoin :exec
INSERT INTO ability_category (ability_id, category_id) VALUES ($1, $2)
`

type CreateAbilityCategoryJoinParams struct {
	AbilityID  int32 `json:"ability_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) CreateAbilityCategoryJoin(ctx context.Context, arg CreateAbilityCategoryJoinParams) error {
	_, err := q.db.Exec(ctx, createAbilityCategoryJoin, arg.AbilityID, arg.CategoryID)
	return err
}
