// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: command_log_channel.sql

package models

import (
	"context"
)

const deleteCommandLogChannel = `-- name: DeleteCommandLogChannel :exec
DELETE FROM command_log_channel
WHERE id = 1
`

func (q *Queries) DeleteCommandLogChannel(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteCommandLogChannel)
	return err
}

const getCommandLogChannel = `-- name: GetCommandLogChannel :one
SELECT channel_id
FROM command_log_channel
WHERE id = 1
`

func (q *Queries) GetCommandLogChannel(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getCommandLogChannel)
	var channel_id string
	err := row.Scan(&channel_id)
	return channel_id, err
}

const setCommandLogChannel = `-- name: SetCommandLogChannel :one
INSERT INTO command_log_channel (id, channel_id)
VALUES (1, $1)
ON CONFLICT (id) DO UPDATE SET
    channel_id = EXCLUDED.channel_id,
    updated_at = NOW()
RETURNING channel_id
`

func (q *Queries) SetCommandLogChannel(ctx context.Context, channelID string) (string, error) {
	row := q.db.QueryRow(ctx, setCommandLogChannel, channelID)
	var channel_id string
	err := row.Scan(&channel_id)
	return channel_id, err
}
