// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: item_category.sql

package models

import (
	"context"
)

const createItemCategoryJoin = `-- name: CreateItemCategoryJoin :exec
INSERT INTO item_category (item_id, category_id) VALUES ($1, $2)
`

type CreateItemCategoryJoinParams struct {
	ItemID     int32 `json:"item_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) CreateItemCategoryJoin(ctx context.Context, arg CreateItemCategoryJoinParams) error {
	_, err := q.db.Exec(ctx, createItemCategoryJoin, arg.ItemID, arg.CategoryID)
	return err
}
