// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: player_ability.sql

package models

import (
	"context"
)

const createPlayerAbilityJoin = `-- name: CreatePlayerAbilityJoin :one
INSERT INTO player_ability (player_id, ability_id, quantity) VALUES ($1, $2, $3) RETURNING player_id, ability_id, quantity
`

type CreatePlayerAbilityJoinParams struct {
	PlayerID  int64 `json:"player_id"`
	AbilityID int32 `json:"ability_id"`
	Quantity  int32 `json:"quantity"`
}

func (q *Queries) CreatePlayerAbilityJoin(ctx context.Context, arg CreatePlayerAbilityJoinParams) (PlayerAbility, error) {
	row := q.db.QueryRow(ctx, createPlayerAbilityJoin, arg.PlayerID, arg.AbilityID, arg.Quantity)
	var i PlayerAbility
	err := row.Scan(&i.PlayerID, &i.AbilityID, &i.Quantity)
	return i, err
}

const listPlayerAbility = `-- name: ListPlayerAbility :many
select ability_info.id, ability_info.name, ability_info.description, ability_info.default_charges, ability_info.any_ability, ability_info.rarity
from player_ability
inner join ability_info on player_ability.ability_id = ability_info.id
where player_ability.player_id = $1
`

func (q *Queries) ListPlayerAbility(ctx context.Context, playerID int64) ([]AbilityInfo, error) {
	rows, err := q.db.Query(ctx, listPlayerAbility, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AbilityInfo
	for rows.Next() {
		var i AbilityInfo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DefaultCharges,
			&i.AnyAbility,
			&i.Rarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
