// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: player_ability.sql

package models

import (
	"context"
)

const createPlayerAbilityJoin = `-- name: CreatePlayerAbilityJoin :one
INSERT INTO player_ability (player_id, ability_id, quantity) VALUES ($1, $2, $3) RETURNING player_id, ability_id, quantity
`

type CreatePlayerAbilityJoinParams struct {
	PlayerID  int32 `json:"player_id"`
	AbilityID int32 `json:"ability_id"`
	Quantity  int32 `json:"quantity"`
}

func (q *Queries) CreatePlayerAbilityJoin(ctx context.Context, arg CreatePlayerAbilityJoinParams) (PlayerAbility, error) {
	row := q.db.QueryRow(ctx, createPlayerAbilityJoin, arg.PlayerID, arg.AbilityID, arg.Quantity)
	var i PlayerAbility
	err := row.Scan(&i.PlayerID, &i.AbilityID, &i.Quantity)
	return i, err
}
