// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: role_perk.sql

package models

import (
	"context"
)

const createRolePerkJoin = `-- name: CreateRolePerkJoin :exec
INSERT INTO role_perk (role_id, perk_id) VALUES ($1, $2)
`

type CreateRolePerkJoinParams struct {
	RoleID int32 `json:"role_id"`
	PerkID int32 `json:"perk_id"`
}

func (q *Queries) CreateRolePerkJoin(ctx context.Context, arg CreateRolePerkJoinParams) error {
	_, err := q.db.Exec(ctx, createRolePerkJoin, arg.RoleID, arg.PerkID)
	return err
}
