// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: role_ability.sql

package models

import (
	"context"
)

const createRoleAbilityJoin = `-- name: CreateRoleAbilityJoin :exec
INSERT INTO role_ability (role_id, ability_id) VALUES ($1, $2)
`

type CreateRoleAbilityJoinParams struct {
	RoleID    int32 `json:"role_id"`
	AbilityID int32 `json:"ability_id"`
}

func (q *Queries) CreateRoleAbilityJoin(ctx context.Context, arg CreateRoleAbilityJoinParams) error {
	_, err := q.db.Exec(ctx, createRoleAbilityJoin, arg.RoleID, arg.AbilityID)
	return err
}
