// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingSyncRun = `-- name: CreatePendingSyncRun :one
INSERT INTO sync_run (source_id, source_name, status, action_counts, run_by, error_message, started_at, phase, progress, total)
VALUES ($1, $2, 'pending', '{}', $3, '', NOW(), 'queued', 0, 4)
RETURNING id, source_id, source_name, status, action_counts, run_by, error_message, started_at, finished_at, phase, progress, total
`

type CreatePendingSyncRunParams struct {
	SourceID   pgtype.Int4 `json:"source_id"`
	SourceName string      `json:"source_name"`
	RunBy      string      `json:"run_by"`
}

func (q *Queries) CreatePendingSyncRun(ctx context.Context, arg CreatePendingSyncRunParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, createPendingSyncRun, arg.SourceID, arg.SourceName, arg.RunBy)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceName,
		&i.Status,
		&i.ActionCounts,
		&i.RunBy,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Phase,
		&i.Progress,
		&i.Total,
	)
	return i, err
}

const createSyncRun = `-- name: CreateSyncRun :one
INSERT INTO sync_run (source_id, source_name, status, action_counts, run_by, error_message, started_at, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, source_id, source_name, status, action_counts, run_by, error_message, started_at, finished_at, phase, progress, total
`

type CreateSyncRunParams struct {
	SourceID     pgtype.Int4        `json:"source_id"`
	SourceName   string             `json:"source_name"`
	Status       string             `json:"status"`
	ActionCounts []byte             `json:"action_counts"`
	RunBy        string             `json:"run_by"`
	ErrorMessage string             `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) CreateSyncRun(ctx context.Context, arg CreateSyncRunParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, createSyncRun,
		arg.SourceID,
		arg.SourceName,
		arg.Status,
		arg.ActionCounts,
		arg.RunBy,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceName,
		&i.Status,
		&i.ActionCounts,
		&i.RunBy,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Phase,
		&i.Progress,
		&i.Total,
	)
	return i, err
}

const getActiveSyncRunBySource = `-- name: GetActiveSyncRunBySource :one
SELECT id, source_id, source_name, status, action_counts, run_by, error_message, started_at, finished_at, phase, progress, total FROM sync_run
WHERE source_id = $1 AND status IN ('pending', 'running')
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetActiveSyncRunBySource(ctx context.Context, sourceID pgtype.Int4) (SyncRun, error) {
	row := q.db.QueryRow(ctx, getActiveSyncRunBySource, sourceID)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceName,
		&i.Status,
		&i.ActionCounts,
		&i.RunBy,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Phase,
		&i.Progress,
		&i.Total,
	)
	return i, err
}

const getSyncRun = `-- name: GetSyncRun :one
SELECT id, source_id, source_name, status, action_counts, run_by, error_message, started_at, finished_at, phase, progress, total FROM sync_run WHERE id = $1
`

func (q *Queries) GetSyncRun(ctx context.Context, id int64) (SyncRun, error) {
	row := q.db.QueryRow(ctx, getSyncRun, id)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceName,
		&i.Status,
		&i.ActionCounts,
		&i.RunBy,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Phase,
		&i.Progress,
		&i.Total,
	)
	return i, err
}

const getSyncSourceByName = `-- name: GetSyncSourceByName :one
SELECT id, name, kind, alignment, url, enabled, created_at, updated_at FROM sync_source WHERE name = $1
`

func (q *Queries) GetSyncSourceByName(ctx context.Context, name string) (SyncSource, error) {
	row := q.db.QueryRow(ctx, getSyncSourceByName, name)
	var i SyncSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Alignment,
		&i.Url,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSyncRuns = `-- name: ListSyncRuns :many
SELECT id, source_id, source_name, status, action_counts, run_by, error_message, started_at, finished_at, phase, progress, total FROM sync_run ORDER BY started_at DESC LIMIT $1
`

func (q *Queries) ListSyncRuns(ctx context.Context, limit int32) ([]SyncRun, error) {
	rows, err := q.db.Query(ctx, listSyncRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncRun
	for rows.Next() {
		var i SyncRun
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.SourceName,
			&i.Status,
			&i.ActionCounts,
			&i.RunBy,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Phase,
			&i.Progress,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncSources = `-- name: ListSyncSources :many
SELECT id, name, kind, alignment, url, enabled, created_at, updated_at FROM sync_source ORDER BY id
`

func (q *Queries) ListSyncSources(ctx context.Context) ([]SyncSource, error) {
	rows, err := q.db.Query(ctx, listSyncSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncSource
	for rows.Next() {
		var i SyncSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Alignment,
			&i.Url,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSyncRun = `-- name: UpdateSyncRun :one
UPDATE sync_run
SET status = $2, phase = $3, progress = $4, total = $5,
    action_counts = $6, error_message = $7, finished_at = $8
WHERE id = $1
RETURNING id, source_id, source_name, status, action_counts, run_by, error_message, started_at, finished_at, phase, progress, total
`

type UpdateSyncRunParams struct {
	ID           int64              `json:"id"`
	Status       string             `json:"status"`
	Phase        string             `json:"phase"`
	Progress     int32              `json:"progress"`
	Total        int32              `json:"total"`
	ActionCounts []byte             `json:"action_counts"`
	ErrorMessage string             `json:"error_message"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateSyncRun(ctx context.Context, arg UpdateSyncRunParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, updateSyncRun,
		arg.ID,
		arg.Status,
		arg.Phase,
		arg.Progress,
		arg.Total,
		arg.ActionCounts,
		arg.ErrorMessage,
		arg.FinishedAt,
	)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceName,
		&i.Status,
		&i.ActionCounts,
		&i.RunBy,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Phase,
		&i.Progress,
		&i.Total,
	)
	return i, err
}

const updateSyncSource = `-- name: UpdateSyncSource :one
UPDATE sync_source
SET url = $2, enabled = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, name, kind, alignment, url, enabled, created_at, updated_at
`

type UpdateSyncSourceParams struct {
	ID      int32  `json:"id"`
	Url     string `json:"url"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) UpdateSyncSource(ctx context.Context, arg UpdateSyncSourceParams) (SyncSource, error) {
	row := q.db.QueryRow(ctx, updateSyncSource, arg.ID, arg.Url, arg.Enabled)
	var i SyncSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Alignment,
		&i.Url,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSyncSourceFromEnv = `-- name: UpsertSyncSourceFromEnv :exec
INSERT INTO sync_source (name, kind, alignment, url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE SET
    url       = CASE WHEN sync_source.url = '' THEN EXCLUDED.url ELSE sync_source.url END,
    kind      = EXCLUDED.kind,
    alignment = EXCLUDED.alignment,
    updated_at = NOW()
`

type UpsertSyncSourceFromEnvParams struct {
	Name      string `json:"name"`
	Kind      string `json:"kind"`
	Alignment string `json:"alignment"`
	Url       string `json:"url"`
}

// Seeds the canonical sources at app startup. The URL from env is only used
// when the row still has the empty placeholder (never overwrites a URL the
// user edited in the web panel).
func (q *Queries) UpsertSyncSourceFromEnv(ctx context.Context, arg UpsertSyncSourceFromEnvParams) error {
	_, err := q.db.Exec(ctx, upsertSyncSourceFromEnv,
		arg.Name,
		arg.Kind,
		arg.Alignment,
		arg.Url,
	)
	return err
}
