
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS abilities CASCADE;
DROP TABLE IF EXISTS perks CASCADE;
DROP TABLE IF EXISTS statuses CASCADE;
DROP TABLE IF EXISTS items CASCADE;

DROP TABLE IF EXISTS roles_abilities CASCADE;
DROP TABLE IF EXISTS roles_perks CASCADE;

DROP TYPE IF EXISTS alignment;
DROP TYPE IF EXISTS action_type;
