<script lang="ts">
  import { onMount } from 'svelte';
  import { page } from '$app/state';
  import { createApiClient } from '$lib/api/client';
  import type { PlayerDetail } from '$lib/player-types';
  let player = $state<PlayerDetail | null>(null); let error = $state(''); let loading = $state(true); let mutating = $state(false); let mutationError = $state('');
  const id = $derived(page.params.id);
  async function load() { loading = true; error = ''; try { player = await createApiClient().get<PlayerDetail>(`/api/v1/players/${id}`); } catch (e) { error = e instanceof Error ? e.message : 'Could not load player'; } finally { loading = false; } }
  async function mutate(path: string, body: unknown) { mutating = true; mutationError = ''; try { player = await createApiClient().post<PlayerDetail>(`/api/v1/players/${id}/${path}`, { headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); } catch (e) { mutationError = e instanceof Error ? e.message : 'Mutation failed'; } finally { mutating = false; } }
  onMount(load);
</script>
<svelte:head><title>Player {id} | Betrayal Admin</title></svelte:head>
<main class="min-h-screen bg-slate-950 p-6 text-slate-100"><header class="mx-auto max-w-5xl border-b border-slate-700 pb-5"><a href="/players" class="text-slate-400">← Players</a><h1 class="mt-2 text-3xl font-semibold">Player {id}</h1></header>
{#if loading}<p role="status" class="mx-auto max-w-5xl py-10">Loading player…</p>{:else if error}<p role="alert" class="mx-auto max-w-5xl py-10 text-red-300">{error}</p>{:else if player}<section class="mx-auto max-w-5xl space-y-6 py-8"><div class="grid grid-cols-2 gap-3 border border-slate-700 p-5"><p>Role: {player.role}</p><p>Alignment: {player.alignment}</p><p>State: {player.alive ? 'Alive' : 'Dead'}</p><p>Coins: {player.coins}</p><p>Luck: {player.luck}</p><p>Item limit: {player.item_limit}</p></div><a class="border border-slate-600 px-4 py-2" href={`/players/${id}/edit`}>Edit player</a>{#if mutationError}<p role="alert" class="text-red-300">{mutationError}</p>{/if}<h2 class="text-xl">Inventory</h2><ul aria-label="Items" class="space-y-2">{#each player.items as item (item.id)}<li>{item.name} × {item.quantity} <button disabled={mutating} onclick={() => mutate('items/remove',{name:item.name})}>Remove</button></li>{:else}<li>No items.</li>{/each}</ul><form onsubmit={(e)=>{e.preventDefault(); const f=new FormData(e.currentTarget); mutate('items/add',{name:f.get('name'),quantity:Number(f.get('quantity')||1)});}} class="flex gap-2"><input name="name" aria-label="Item name" placeholder="Item name"/><input name="quantity" type="number" min="1" value="1" aria-label="Quantity"/><button disabled={mutating}>Add item</button></form><h2 class="text-xl">Notes</h2><ul aria-label="Notes">{#each player.notes as note (note.id)}<li>{note.info} <button disabled={mutating} onclick={() => mutate('notes/remove',{note_id:note.id})}>Remove</button></li>{:else}<li>No notes.</li>{/each}</ul></section>{/if}</main>
