// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

// AbilityRow represents an ability in the role abilities list
type AbilityRow struct {
	ID             int32
	Name           string
	Description    string
	DefaultCharges int32
	AnyAbility     bool
	Rarity         string
}

func RoleAbilities(roleID int32, abilities []AbilityRow) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if len(abilities) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"p-4 text-center text-dust\">No abilities associated with this role</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"divide-y divide-dust/20\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, ability := range abilities {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"p-4\" id=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var2 string
				templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("ability-%d", ability.ID))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/partials/role_abilities.templ`, Line: 23, Col: 63}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"><form hx-put=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("/roles/%d/abilities/%d", roleID, ability.ID))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/partials/role_abilities.templ`, Line: 25, Col: 72}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" hx-swap=\"none\" class=\"space-y-3\"><div class=\"flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3\"><div class=\"flex-1 grid grid-cols-1 md:grid-cols-2 gap-3\"><div><label class=\"block text-xs font-medium text-dust mb-1\">Name</label> <input type=\"text\" name=\"name\" value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(ability.Name)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/partials/role_abilities.templ`, Line: 36, Col: 30}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" class=\"w-full px-3 py-2 text-sm border border-dust rounded bg-parchment text-wood focus:outline-none focus:ring-1 focus:ring-leather\"></div><div class=\"flex gap-2\"><div class=\"flex-1\"><label class=\"block text-xs font-medium text-dust mb-1\">Charges</label> <input type=\"number\" name=\"default_charges\" value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", ability.DefaultCharges))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/partials/role_abilities.templ`, Line: 46, Col: 60}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" class=\"w-full px-3 py-2 text-sm border border-dust rounded bg-parchment text-wood focus:outline-none focus:ring-1 focus:ring-leather\"></div><div class=\"flex-1\"><label class=\"block text-xs font-medium text-dust mb-1\">Rarity</label> <select name=\"rarity\" class=\"w-full px-3 py-2 text-sm border border-dust rounded bg-parchment text-wood focus:outline-none focus:ring-1 focus:ring-leather\"><option value=\"COMMON\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if ability.Rarity == "COMMON" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " selected")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, ">COMMON</option> <option value=\"UNCOMMON\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if ability.Rarity == "UNCOMMON" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, " selected")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, ">UNCOMMON</option> <option value=\"RARE\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if ability.Rarity == "RARE" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, " selected")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, ">RARE</option> <option value=\"EPIC\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if ability.Rarity == "EPIC" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, " selected")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, ">EPIC</option> <option value=\"LEGENDARY\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if ability.Rarity == "LEGENDARY" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, " selected")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, ">LEGENDARY</option> <option value=\"MYTHICAL\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if ability.Rarity == "MYTHICAL" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, " selected")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, ">MYTHICAL</option> <option value=\"ROLE_SPECIFIC\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if ability.Rarity == "ROLE_SPECIFIC" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, " selected")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, ">ROLE_SPECIFIC</option> <option value=\"UNIQUE\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if ability.Rarity == "UNIQUE" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, " selected")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, ">UNIQUE</option></select></div></div></div></div><div><label class=\"block text-xs font-medium text-dust mb-1\">Description</label> <textarea name=\"description\" rows=\"2\" class=\"w-full px-3 py-2 text-sm border border-dust rounded bg-parchment text-wood focus:outline-none focus:ring-1 focus:ring-leather\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(ability.Description)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/partials/role_abilities.templ`, Line: 75, Col: 29}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "</textarea></div><div class=\"flex items-center justify-between\"><label class=\"flex items-center gap-2 text-sm text-wood\"><input type=\"checkbox\" name=\"any_ability\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if ability.AnyAbility {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, " checked")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, " class=\"rounded border-dust text-leather focus:ring-leather\"> Any Ability (can be given to any role)</label><div class=\"flex gap-2\"><button type=\"submit\" class=\"btn-primary text-sm px-3 py-1\">Save</button> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, showDeleteConfirm(roleID, ability.ID, ability.Name, "ability"))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, "<button type=\"button\" class=\"btn-danger text-sm px-3 py-1\" onclick=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 templ.ComponentScript = showDeleteConfirm(roleID, ability.ID, ability.Name, "ability")
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7.Call)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "\">Remove</button></div></div></form></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

func showDeleteConfirm(roleID int32, itemID int32, itemName string, itemType string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_showDeleteConfirm_d1e8`,
		Function: `function __templ_showDeleteConfirm_d1e8(roleID, itemID, itemName, itemType){showDeleteModal(
		` + "`" + `Are you sure you want to remove "${itemName}" from this role? This only removes the association, not the ${itemType} itself.` + "`" + `,
		function() {
			htmx.ajax('DELETE', ` + "`" + `/roles/${roleID}/${itemType === 'ability' ? 'abilities' : 'perks'}/${itemID}` + "`" + `, {
				target: ` + "`" + `#${itemType}-${itemID}` + "`" + `,
				swap: 'outerHTML'
			}).then(function() {
				// Refresh the list
				htmx.ajax('GET', ` + "`" + `/roles/${roleID}/${itemType === 'ability' ? 'abilities' : 'perks'}` + "`" + `, {
					target: ` + "`" + `#${itemType === 'ability' ? 'abilities' : 'perks'}-list` + "`" + `,
					swap: 'innerHTML'
				});
			});
		}
	);
}`,
		Call:       templ.SafeScript(`__templ_showDeleteConfirm_d1e8`, roleID, itemID, itemName, itemType),
		CallInline: templ.SafeScriptInline(`__templ_showDeleteConfirm_d1e8`, roleID, itemID, itemName, itemType),
	}
}

var _ = templruntime.GeneratedTemplate
