<script lang="ts">
  import { onMount } from 'svelte';
  import { createApiClient } from '$lib/api/client';
  type Player = { id: string; label: string; alive: boolean; coins: number; luck: number; item_limit: number; alignment: string; role: string };
  type Member = { id: string; username: string; nickname?: string; bot: boolean };
  let players = $state<Player[] | null>(null); let loadError = $state<string | null>(null); let search = $state(''); let filterState = $state<'all' | 'alive' | 'dead'>('all');
  const api = createApiClient();
  onMount(async () => { try { const [raw, resources] = await Promise.all([api.get<Omit<Player, 'label'>[]>('/api/v1/players'), api.get<{ members: Member[] }>('/api/v1/discord/resources').catch(() => ({ members: [] }))]); const members = new Map(resources.members.map((member) => [member.id, member])); players = raw.map((player, index) => { const member = members.get(player.id); return { ...player, label: member?.nickname || member?.username || `Player ${index + 1}` }; }); } catch (error) { loadError = error instanceof Error ? error.message : 'Could not load players'; } });
  let visiblePlayers = $derived((players ?? []).filter((player) => { const q = search.trim().toLowerCase(); const matchesSearch = !q || `${player.label} ${player.role} ${player.alignment}`.toLowerCase().includes(q); return matchesSearch && (filterState === 'all' || (filterState === 'alive' ? player.alive : !player.alive)); }));
  let aliveCount = $derived((players ?? []).filter((player) => player.alive).length); let deadCount = $derived((players ?? []).filter((player) => !player.alive).length);
</script>
<svelte:head><title>Players | Betrayal Admin</title><meta name="description" content="Betrayal game players" /></svelte:head>
<main class="page-shell"><header class="page-header"><div><p class="eyebrow">Game operations / roster</p><h1 class="display-title">Players</h1><p class="lede">Keep the cast, state, and resources in view without decoding Discord snowflakes.</p></div><a href="/players/new" class="btn btn-primary">＋ Add player</a></header>
{#if loadError}<p class="state state-error" role="alert">{loadError}</p>{:else if !players}<p class="state" role="status">Loading player roster…</p>{:else}<section class="stat-grid" aria-label="Roster summary"><article class="stat-card"><span class="eyebrow">Total roster</span><strong>{players.length}</strong><span>registered players</span></article><article class="stat-card stat-live"><span class="eyebrow">In play</span><strong>{aliveCount}</strong><span>alive now</span></article><article class="stat-card stat-dead"><span class="eyebrow">Out</span><strong>{deadCount}</strong><span>eliminated</span></article></section><section class="toolbar"><div class="search-wrap"><span aria-hidden="true">⌕</span><input bind:value={search} placeholder="Search by name, role, or alignment" aria-label="Search players" /></div><select bind:value={filterState} aria-label="Filter player state"><option value="all">Everyone</option><option value="alive">Alive only</option><option value="dead">Dead only</option></select><p class="toolbar-count">{visiblePlayers.length} shown</p></section>{#if players.length === 0}<p class="state">No players are available yet. Add the first player to start the roster.</p>{:else if visiblePlayers.length === 0}<p class="state">No players match that search.</p>{:else}<div class="player-grid">{#each visiblePlayers as player (player.id)}<a class="player-card" href={`/players/${player.id}`} aria-label={`Open ${player.label} profile`}><div class="player-card-top"><span class:status-dead={!player.alive} class="status-dot"></span><span class="status-label">{player.alive ? 'Alive' : 'Dead'}</span><span class="card-arrow">↗</span></div><h2>{player.label}</h2><p class="player-role">{player.role}</p><div class="player-meta"><span><small>Alignment</small>{player.alignment}</span><span><small>Coins</small>{player.coins}</span><span><small>Luck</small>{player.luck}</span></div><div class="card-footer"><span>Capacity {player.item_limit}</span><span>View profile</span></div></a>{/each}</div>{/if}{/if}</main>
