<script lang="ts">
  import { onMount } from 'svelte';
  import FuzzySelect from '$lib/forms/FuzzySelect.svelte';
  import { createApiClient } from '$lib/api/client';
  type Player = { id: string; alive: boolean; coins: number; luck: number; item_limit: number; alignment: string; role: string };
  let players = $state<Player[] | null>(null);
  let loadError = $state<string | null>(null);
  let search = $state('');
  let filterState = $state<'all' | 'alive' | 'dead'>('all');
  onMount(async () => { try { players = await createApiClient().get<Player[]>('/api/v1/players'); } catch (error) { loadError = error instanceof Error ? error.message : 'Could not load players'; } });
  let visiblePlayers = $derived((players ?? []).filter((player: Player) => { const q = search.trim().toLowerCase(); const matchesSearch = !q || `${player.id} ${player.role} ${player.alignment}`.toLowerCase().includes(q); return matchesSearch && (filterState === 'all' || (filterState === 'alive' ? player.alive : !player.alive)); }));
</script>
<svelte:head><title>Players | Betrayal Admin</title><meta name="description" content="Betrayal game players" /></svelte:head>
<main class="min-h-screen bg-slate-950 p-6 text-slate-100"><header class="mx-auto flex max-w-6xl items-end justify-between border-b border-slate-700 pb-5"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">Betrayal Admin</p><h1 class="mt-2 text-3xl font-semibold">Players</h1></div><a href="/players/new" class="rounded border border-teal-400 px-4 py-2 text-sm text-teal-300 hover:bg-teal-400/10">New player</a></header>{#if loadError}<p class="mx-auto max-w-6xl py-10 text-red-300" role="alert">{loadError}</p>{:else if !players}<p class="mx-auto max-w-6xl py-10 text-slate-300" role="status">Loading players…</p>{:else}<section class="mx-auto mt-6 max-w-6xl rounded border border-slate-800 bg-[#0d111b] p-4"><div class="grid gap-3 md:grid-cols-[1fr_auto]"><input bind:value={search} placeholder="Search player ID, role, or alignment…" aria-label="Search players" class="bg-slate-900 p-3" /><select bind:value={filterState} aria-label="Filter player state" class="bg-slate-900 p-3"><option value="all">All states</option><option value="alive">Alive only</option><option value="dead">Dead only</option></select></div><p class="mt-3 text-sm text-slate-500">Showing {visiblePlayers.length} of {players.length} players</p></section>{#if visiblePlayers.length === 0}<p class="mx-auto max-w-6xl py-10 text-slate-300">No players match this search.</p>{:else}<div class="mx-auto max-w-6xl overflow-x-auto py-8"><table class="w-full border-collapse text-left" aria-label="Players"><thead class="border-b border-slate-700 text-sm uppercase tracking-wide text-slate-400"><tr><th class="p-3">ID</th><th class="p-3">Role</th><th class="p-3">Alignment</th><th class="p-3">State</th><th class="p-3">Coins</th><th class="p-3">Luck</th><th class="p-3">Item limit</th></tr></thead><tbody>{#each visiblePlayers as player (player.id)}<tr class="border-b border-slate-800"><td class="p-3 font-mono"><a class="text-teal-300 hover:underline" href={`/players/${player.id}`}>{player.id}</a></td><td class="p-3">{player.role}</td><td class="p-3">{player.alignment}</td><td class="p-3">{player.alive ? 'Alive' : 'Dead'}</td><td class="p-3">{player.coins}</td><td class="p-3">{player.luck}</td><td class="p-3">{player.item_limit}</td></tr>{/each}</tbody></table></div>{/if}{/if}</main>
